version: '3'

volumes:
  dnd-campaign-data:
    external: true

services:
  backend-fastapi:
    environment:
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@db/dnd-campaign
      WAIT_HOSTS: db:5432
      PORT: 8000
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app

  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "15432:5432"
    volumes:
      - dnd-campaign-data:/var/lib/postgresql/data
